env:
    browser: true
    es2021: true
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: "latest"
    sourceType: "module"
extends:
    - standard-with-typescript
    - plugin:react/recommended
plugins:
    - "@typescript-eslint"
    - react

    "rules": {
    - "space-before-function-paren": "off"
    - "react/react-in-jsx-scope": "off"
}

"settings": { "react": { "version": "detect" } }
